<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.0.1</Version>
    <AssemblyName>DSH-Desktop-Webview</AssemblyName>
    <RootNamespace>DshDesktop.App</RootNamespace>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    <PackageReference Include="PixiEditor.ColorPicker" Version="3.4.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DshDesktop.Application\DshDesktop.Application.csproj" />
    <ProjectReference Include="..\DshDesktop.Domain\DshDesktop.Domain.csproj" />
    <ProjectReference Include="..\DshDesktop.Infrastructure\DshDesktop.Infrastructure.csproj" />
  </ItemGroup>

</Project>
